POST http://127.0.0.1:8080/customer
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0

{
  "id": "100",
  "firstName": "Jane",
  "lastName": "Smith",
  "email": "jane.smith@company.com"
}


###
POST http://127.0.0.1:8080/customer
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0

{
  "id": "200",
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@company.com"
}

###
POST http://127.0.0.1:8080/customer
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0

{
  "id": "300",
  "firstName": "Mary",
  "lastName": "Smith",
  "email": "mary.smith@company.com"
}

###
GET http://127.0.0.1:8080/customer
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0

###
GET http://127.0.0.1:8080/customer/200
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0

###
GET http://127.0.0.1:8080/customer/500
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0

###
DELETE http://127.0.0.1:8080/customer/100
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0

###
DELETE http://127.0.0.1:8080/customer/100

###
DELETE http://127.0.0.1:8080/customer/500
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjdXN0b21lcnMiLCJpc3MiOiJodHRwOi8vMC4wLjAuMDo4MDgwIiwiZXhwIjoxNzAxMDMwMjgwLCJ1c2VySWQiOiIxIn0.GO10yTwLJo15EBuuxaF-PSnc4wq52Aw5FsOlRLiGfQ0
